import React from 'react'
import Link from 'next/link'
import Navbar from '../components/Navbar'

export default function averageReturn() {
    const navigation = [
        { name: 'Learn', href: 'learn' },
        { name: 'Dictionary', href: 'dictionary' },
        { name: 'About', href: 'about' },
    ];

    return (
        <div className="flex flex-col bg-white min-h-screen">
            <Navbar navigation={navigation} />

            <div className="mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8">
                <div className="mb-4 text-sm">
                    <Link href="/" class="text-green-500 font-medium underline">Home</Link>
                    <span className="px-2" aria-hidden="true">/</span>
                    <Link class="text-green-500 font-medium underline" href="/dictionary/">Dictionary</Link>
                    <span className="px-2" aria-hidden="true">/</span>
                    <span className="text-gray-700">Average Return</span>
                </div>

                <section>
                    <h1 className="text-3xl font-bold tracking-tight text-gray-900">Average Return</h1>
                    <p className="mt-4">Average return is the average gain or loss generated by an investment or portfolio over a specific period of time. It is a measure used to assess the historical performance
                    of an investment and can provide insight into its potential future performance.</p>
                    <h2 className="text-2xl font-bold tracking-tight text-gray-900 mt-4">What You Need To Know</h2>
                    <p className="mt-2">The average return is calculated by summing the returns of an investment over a given period and dividing it by the number of periods. For example, if an investment returns
                    5% in the first year, 10% in the second year, and -2% in the third year, the average return over the 3-year period would be (5% + 10% - 2%) / 3 = 4.33%.</p>
                    <p className="mt-2">Average return is often expressed as an annualized figure to allow for easier comparison between different investments or time periods. This is done by calculating the geometric
                    mean of the individual period returns. The geometric mean takes compounding into account and provides a more accurate representation of the true average return over multiple periods.</p>
                    <p className="mt-2">Note that average return alone does not capture the volatility or variability of investment returns. It is a simple measure that provides an overview of the historical performance
                    but does not guarantee similar results in the future. Investors should consider other factors such as risk, diversification, and their individual investment goals when evaluating the attractiveness of
                    an investment.</p>
                    <p className="mt-2">Average return is commonly used in financial analysis, portfolio management, and investment planning to assess the historical performance of investments, compare different investment
                    options, and estimate potential future returns. However, it is essential to analyze a comprehensive set of metrics and consider the investment&apos;s risk profile and suitability to make informed
                    investment decisions.</p>
                </section>
            </div>
        </div>
    )
}