import React from 'react'
import Link from 'next/link'
import Navbar from '../components/Navbar'

export default function creditScore() {
    const navigation = [
        { name: 'Learn', href: 'learn' },
        { name: 'Dictionary', href: 'dictionary' },
        { name: 'About', href: 'about' },
    ]

    return (
        <div className="flex flex-col bg-white min-h-screen">
            <Navbar navigation={navigation} />

            <div className="mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8">
                <div className="mb-4 text-sm">
                    <Link href="/" class="text-green-500 font-medium underline">Home</Link>
                    <span className="px-2" aria-hidden="true">/</span>
                    <Link class="text-green-500 font-medium underline" href="/dictionary/">Dictionary</Link>
                    <span className="px-2" aria-hidden="true">/</span>
                    <span className="text-gray-700">Credit Score</span>
                </div>

                <section>
                    <h1 className="text-3xl font-bold tracking-tight text-gray-900">Credit Score</h1>
                    <p className="mt-4">A credit score is a numerical representation of an individual&apos;s creditworthiness, indicating their likelihood of repaying debts and managing credit responsibly. It is calculated
                    based on various factors, including payment history, credit utilization, length of credit history, types of credit used, and recent credit inquiries. A higher credit score generally signifies a lower credit
                    risk and can result in easier access to credit and better borrowing terms.</p>
                    <h2 className="text-2xl font-bold tracking-tight text-gray-900 mt-4">What You Need To Know</h2>
                    <p className="mt-2">Credit scores are determined by considering various factors. Payment history, which reflects the individual&apos;s track record of making on-time payments, is one of the most significant factors. Credit
                    utilization, the percentage of available credit being used, is another important factor. Length of credit history, types of credit used (such as credit cards, loans, and mortgages), and recent credit
                    inquiries also impact the credit score.</p>
                    <p className="mt-2">Credit scores are generated by credit reporting agencies, such as Experian, TransUnion, and Equifax. These agencies collect and analyze credit information from various sources, including lenders and
                    creditors, to calculate credit scores. Each agency may use slightly different scoring models, resulting in some variation in credit scores.</p>
                    <p className="mt-2">Credit scores typically range from 300 to 850, with higher scores indicating better creditworthiness. While the specific range categories may vary, generally a score above 700 is considered good, while
                    a score above 800 is considered excellent. Lower scores may indicate higher credit risk, potentially resulting in difficulties in obtaining credit or higher interest rates.</p>
                    <p className="mt-2">Building a positive credit history over time is crucial for maintaining a good credit score. Making payments on time, keeping credit utilization low, and avoiding excessive debt are essential practices
                    for establishing and improving creditworthiness.</p>
                    <p className="mt-2">Regularly monitoring credit reports and credit scores is essential for understanding one&apos;s creditworthiness and detecting any errors or fraudulent activity. Review credit reports from all three major
                    credit reporting agencies annually and take steps to correct any inaccuracies.</p>
                </section>
            </div>
        </div>
    )
}
