import React from 'react'
import Link from 'next/link'
import Navbar from '../components/Navbar'

export default function dividends() {
    const navigation = [
        { name: 'Learn', href: 'learn' },
        { name: 'Dictionary', href: 'dictionary' },
        { name: 'About', href: 'about' },
    ]

    return (
        <div className="flex flex-col bg-white min-h-screen">
            <Navbar navigation={navigation} />

            <div className="mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8">
                <div className="mb-4 text-sm">
                    <Link href="/" class="text-green-500 font-medium underline">Home</Link>
                    <span className="px-2" aria-hidden="true">/</span>
                    <Link class="text-green-500 font-medium underline" href="/dictionary/">Dictionary</Link>
                    <span className="px-2" aria-hidden="true">/</span>
                    <span className="text-gray-700">Dividends</span>
                </div>

                <section>
                    <h1 className="text-3xl font-bold tracking-tight text-gray-900">Dividends</h1>
                    <p className="mt-4">Dividends are payments made by corporations to their shareholders to distribute their profits and provide investors with a source of passive income. They are typically paid in cash, but they can also be
                    issued as additional shares of stock or other forms of property.</p>
                    <h2 className="text-2xl font-bold tracking-tight text-gray-900 mt-4">What You Need To Know</h2>
                    <p className="mt-2">Dividend payments can provide a steady stream of income, which can be especially beneficial for retirees or individuals seeking passive income. They are commonly paid in cash, with shareholders receiving
                    a specific amount of money per share owned. However, companies may also distribute dividends in the form of additional shares of stock, known as stock dividends or bonus shares. Other forms of dividends can include property
                    dividends, where shareholders receive assets or goods instead of cash.</p>
                    <p className="mt-2">Dividend yield is a financial ratio that measures the annual dividend payments relative to the market price of the stock. It indicates the return on investment generated by the dividend income. Dividend
                    yield is calculated by dividing the annual dividend per share by the stock&apos;s current market price.</p>
                    <p className="mt-2">Companies determine their dividend policies, which can vary depending on factors such as profitability, cash flow, growth opportunities, and capital needs. Some companies have a consistent history of
                    paying dividends, while others may choose to reinvest profits back into the business for expansion or debt reduction.</p>
                    <p className="mt-2">Dividend payments follow specific timelines and have associated dates. The declaration date is when the company&apos;s board of directors announces the dividend payment. The ex-dividend date is the date on
                    or after which a buyer of the stock will not be entitled to the upcoming dividend if they haven&apos;t purchased the shares yet. The record date is the date on which shareholders must be registered to receive
                    the dividend, and the payment date is when the dividend is actually distributed to eligible shareholders.</p>
                    <p className="mt-2">Dividends are generally subject to taxation, though at a different rate than ordinary income. The the tax treatment can vary depending on factors such as the jurisdiction, type of dividend, and the
                    recipient&apos;s tax status. Consult with tax professionals or refer to tax regulations in your country to understand the specific tax implications of receiving dividends.</p>
                </section>
            </div>
        </div>
    )
}