import React from 'react'
import Link from 'next/link'
import Navbar from '../components/Navbar'

export default function yie() {
    const navigation = [
        { name: 'Learn', href: 'learn' },
        { name: 'Dictionary', href: 'dictionary' },
        { name: 'About', href: 'about' },
    ]

    return (
        <div className="flex flex-col bg-white min-h-screen">
            <Navbar navigation={navigation} />

            <div className="mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8">
                <div className="mb-4 text-sm">
                    <Link href="/" class="text-green-500 font-medium underline">Home</Link>
                    <span className="px-2" aria-hidden="true">/</span>
                    <Link class="text-green-500 font-medium underline" href="/dictionary/">Dictionary</Link>
                    <span className="px-2" aria-hidden="true">/</span>
                    <span className="text-gray-700">Yield</span>
                </div>

                <section>
                    <h1 className="text-3xl font-bold tracking-tight text-gray-900">Yield</h1>
                    <p className="mt-4">Yield is the return on investment or the income generated by an investment relative to its cost. It represents the percentage or rate of return that an investor receives from an investment.</p>
                    <h2 className="text-2xl font-bold tracking-tight text-gray-900 mt-4">What You Need To Know</h2>
                    <p className="mt-2">Yield can take various forms depending on the type of investment. For example, in bond investments, yield refers to the interest payments received by the bondholder. In dividend stocks,
                    yield represents the dividend income received relative to the stock price. In real estate, yield may refer to rental income relative to the property value. It is often used as an indicator of the income potential
                    or profitability of an investment. Higher yield generally suggests higher income or returns, but it is essential to assess the risk-return trade-off and consider factors such as credit risk, market volatility, and
                    economic conditions when evaluating investment opportunities based on yield.</p>
                    <p className="mt-2">Yield plays a significant role in fixed income investments, such as bonds or certificates of deposit (CDs). Yield helps investors understand the income they can expect to receive over the
                    investment&apos;s lifespan, considering factors like coupon payments, interest rates, and the maturity of the investment.</p>
                </section>
            </div>
        </div>
    )
}